# Generated by Django 6.0.3 on 2026-03-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="accessrolerule",
            unique_together={("role", "element")},
        ),
    ]
